
#define LED_EACH_SIDE 10
#define NUM_LEDS LED_EACH_SIDE * 4
#define NUM_LEDS_HALF (LED_EACH_SIDE + LED_EACH_SIDE)
#define DATA_PIN 5
#define MAX_SERIAL_LENGTH 100
#define START_TAX '\x01'
#define END_TAX '\x02'


#define RANDOM_LIGHT_NUM LED_EACH_SIDE


#define RANDOM_LINE_NUM 10
#define RANDOM_LINE_LENGTH 5


